---
"dbt_astro_demo":
  target: dev
  outputs:   
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD', '') }}"
      private_key: "{{ env_var('SF_SERVICE_USER_KEY') }}"
      private_key_passphrase: ""  # Explicit empty string
      role: "{{ env_var('SF_ROLE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      schema: "{{ env_var('SF_SCHEMA') }}"
      threads: 4
      reuse_connections: True
