version: 2

models:
  - name: dim_customer
    description: Dimensional list of customers
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: integer
        constraints:
          - type: not_null
        tests:
          - unique

      - name: customer_name
        data_type: varchar(100)
        constraints:
          - type: not_null

      - name: customer_email
        data_type: varchar(50)
      
      - name: customer_phone
        data_type: varchar(50)


  - name: dim_product
    description: Dimensional list of products
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        data_type: varchar(10)
        constraints:
          - type: not_null
        tests:
          - unique

      - name: product_name
        data_type: varchar(30)
        constraints:
          - type: not_null
        tests:
          - unique
  

  - name: fct_order
    description: Fact table for orders
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: integer
        constraints:
          - type: not_null

      - name: customer_id
        data_type: integer
        constraints:
          - type: not_null

      - name: order_date
        data_type: date
        constraints:
          - type: not_null

      - name: order_total
        data_type: integer
        constraints:
          - type: not_null
  

  - name: fct_order_item
    description: Fact table for order items
    config:
      contract:
        enforced: true
    columns:
      - name: order_item_key
        data_type: varchar
        constraints:
          - type: not_null
        tests:
          - unique

      - name: order_id
        data_type: integer
        constraints:
          - type: not_null

      - name: product_id
        data_type: varchar(10)
        constraints:
          - type: not_null

      - name: order_date
        data_type: date
        constraints:
          - type: not_null
      
      - name: quantity
        data_type: integer
        constraints:
          - type: not_null
      
      - name: unit_price
        data_type: decimal(8, 2)
        constraints:
          - type: not_null
      
      - name: line_total
        data_type: decimal(8, 2)
        constraints:
          - type: not_null
